AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: metrics-cloudwatch-embedded-integration-test

Parameters:
  LambdaRole:
    Type: String
  SecretToken:
    Type: String

Globals:
  Function:
    Timeout: 3

Resources:
  API:
    Type: AWS::Serverless::Api
    Properties:
      StageName: integ-test

  SimpleFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: rust-cargolambda
      BuildProperties:
        Binary: simple
    Properties:
      CodeUri: ./
      Handler: bootstrap
      Runtime: provided.al2023
      Role: !Ref LambdaRole
      
  HttpFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: rust-cargolambda
      BuildProperties:
        Binary: http
    Properties:
      CodeUri: ./
      Handler: bootstrap
      Runtime: provided.al2023
      Role: !Ref LambdaRole
      Events:
        HelloWorld:
          Type: Api
          Properties:
            RestApiId: !Ref API
            Path: /hello
            Method: get

Outputs:
  HttpApiEndpoint:
    Description: "API Gateway endpoint URL for metrics-cloudwatch-embedded integration test"
    Value: !Sub "https://${API}.execute-api.${AWS::Region}.amazonaws.com/integ-test/hello/"